---
- hosts: all
  gather_facts: true
  tasks:
    - include_role:
        name: podman_runlabel
      vars:
        runlabel_image: runlabel_test
        ansible_python_interpreter: "{{ _ansible_python_interpreter }}"
