---
- hosts: all
  gather_facts: true
  tasks:
    - include_role:
        name: podman_secret_info
      vars:
        idem_image: idempotency_test
        ansible_python_interpreter: "{{ _ansible_python_interpreter }}"
