namespace: containers
name: podman
version: 0.3.0
readme: README.md
authors: Podman
description: Podman container Ansible modules
license: Apache-2.0
tags:
  - containers
  - podman
  - libpod
dependencies: {}
repository: https://github.com/containers/ansible-podman-collections.git
documentation: https://github.com/containers/ansible-podman-collections
homepage: https://github.com/containers/ansible-podman-collections
issues: https://github.com/containers/ansible-podman-collections/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
build_ignore:
  - build_artifact
  - "*.tar.gz"
  - zuul.yaml
  - .gitignore
  - tests/output
  - ".history"
  - ".vscode"
  - ".idea"
