name: Podman login info

on:
  push:
    paths:
      - '.github/workflows/podman_login_info.yml'
      - '.github/workflows/reusable-module-test.yml'
      - 'ci/*.yml'
      - 'ci/run_containers_tests.sh'
      - 'ci/playbooks/containers/podman_login_info.yml'
      - 'plugins/modules/podman_login_info.py'
      - 'tests/integration/targets/podman_login_info/**'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/podman_login_info.yml'
      - '.github/workflows/reusable-module-test.yml'
      - 'ci/*.yml'
      - 'ci/run_containers_tests.sh'
      - 'ci/playbooks/containers/podman_login_info.yml'
      - 'plugins/modules/podman_login_info.py'
      - 'tests/integration/targets/podman_login_info/**'
  schedule:
    - cron: 4 0 * * *  # Run daily at 0:03 UTC

jobs:
  test_podman_login_info:
    uses: ./.github/workflows/reusable-module-test.yml
    with:
      module_name: 'podman_login_info'
      display_name: 'Podman login info'
