name: Podman quadlet build

on:
  push:
    paths:
      - ".github/workflows/podman_quadlet_build.yml"
      - ".github/workflows/reusable-module-test.yml"
      - ci/playbooks/*.yml
      - "ci/run_containers_tests.sh"
      - "ci/playbooks/containers/podman_quadlet_build.yml"
      - "plugins/modules/podman_quadlet_build.py"
      - "plugins/module_utils/podman/quadlet.py"
      - "tests/integration/targets/podman_quadlet_build/**"
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/podman_quadlet_build.yml"
      - ".github/workflows/reusable-module-test.yml"
      - ci/playbooks/*.yml
      - "ci/run_containers_tests.sh"
      - "ci/playbooks/containers/podman_quadlet_build.yml"
      - "plugins/modules/podman_quadlet_build.py"
      - "plugins/module_utils/podman/quadlet.py"
      - "tests/integration/targets/podman_quadlet_build/**"
  schedule:
    - cron: 7 0 * * * # Run daily at 0:07 UTC

jobs:
  test_podman_quadlet_build:
    uses: ./.github/workflows/reusable-module-test.yml
    with:
      module_name: "podman_quadlet_build"
      display_name: "Podman quadlet build"
      extra_collections: "ansible.posix"
